In [1]:
import network as nn

In [2]:
%reload_ext autoreload
%autoreload 2
import numpy as np

In [10]:
data_set = [
    (np.array([0,0,0,0]), np.array([0])),
    (np.array([0,0,0,1]), np.array([1])),
    (np.array([0,0,1,0]), np.array([1])),
    (np.array([0,0,1,1]), np.array([0])),
    (np.array([0,1,0,0]), np.array([1])),
    (np.array([0,1,0,1]), np.array([0])),
    (np.array([0,1,1,0]), np.array([0])),
    (np.array([0,1,1,1]), np.array([1])),
    (np.array([1,0,0,0]), np.array([1])),
    (np.array([1,0,0,1]), np.array([0])),
    (np.array([1,0,1,0]), np.array([0])),
    (np.array([1,0,1,1]), np.array([1])),
    (np.array([1,1,0,0]), np.array([0])),
    (np.array([1,1,0,1]), np.array([1])),
    (np.array([1,1,1,0]), np.array([1])),
    (np.array([1,1,1,1]), np.array([0])),
]

In [17]:
train = data_set[:12]
test = data_set[12:]

In [18]:
import network as nn
net = nn.Network([4,4,1])

In [34]:
net.reset()
net.SGD(data_set, 64, 4, 100, data_set)

[[7.99887579]]
Epoch 0: 8 / 16
[[8.00003857]]
Epoch 1: 8 / 16
[[8.00004981]]
Epoch 2: 8 / 16
[[8.00007461]]
Epoch 3: 8 / 16
[[8.00019635]]
Epoch 4: 8 / 16
[[7.99998946]]
Epoch 5: 8 / 16
[[7.9999812]]
Epoch 6: 8 / 16
[[8.00002356]]
Epoch 7: 8 / 16
[[8.00095268]]
Epoch 8: 8 / 16
[[7.99811353]]
Epoch 9: 8 / 16
[[7.99868603]]
Epoch 10: 8 / 16
[[7.99997069]]
Epoch 11: 8 / 16
[[7.9999694]]
Epoch 12: 8 / 16
[[7.99996799]]
Epoch 13: 8 / 16
[[7.99996644]]
Epoch 14: 8 / 16
[[7.99996474]]
Epoch 15: 8 / 16
[[7.99996286]]
Epoch 16: 8 / 16
[[7.99996076]]
Epoch 17: 8 / 16
[[7.99995842]]
Epoch 18: 8 / 16
[[7.99995579]]
Epoch 19: 8 / 16
[[7.9999528]]
Epoch 20: 8 / 16
[[7.99994939]]
Epoch 21: 8 / 16
[[7.99994544]]
Epoch 22: 8 / 16
[[7.99994084]]
Epoch 23: 8 / 16
[[7.99993539]]
Epoch 24: 8 / 16
[[7.99992885]]
Epoch 25: 8 / 16
[[7.99992089]]
Epoch 26: 8 / 16
[[7.99991091]]
Epoch 27: 8 / 16
[[7.99989814]]
Epoch 28: 8 / 16
[[7.9998811]]
Epoch 29: 8 / 16
[[7.99985744]]
Epoch 30: 8 / 16
[[7.99982245]]
Epoch 3

In [20]:
net.weights

[array([[ 0.0113411 , -1.00001069,  0.24631305,  0.09661611],
        [ 0.46426021,  0.5162463 , -2.99988128, -2.86983416],
        [-0.01823782, -0.32157668, -1.66558929, -1.15106905],
        [ 0.17645416, -0.50764209, -1.20228797, -0.46824712]]),
 array([[ 0.76874153,  1.79528682,  0.24719217, -0.25154971]])]

In [21]:
net.biases

[array([[-2.59218928],
        [-0.25866832],
        [-1.109937  ],
        [-1.40528882]]), array([[0.13924341]])]

In [22]:
net.feedforward(np.array([1,1,1,1]))

array([[0.54339021]])

In [3]:
data = [
    (np.array([[0,0]]).T, np.array([[0]])),
    (np.array([[0,1]]).T, np.array([[0]])),
    (np.array([[1,0]]).T, np.array([[0]])),
    (np.array([[1,1]]).T, np.array([[1]])),
]

In [4]:
mynet = nn.Network([2,2,1])

In [5]:
mynet.SGD(data, 1000, 1, 1)

Epoch 0 complete
Epoch 1 complete
Epoch 2 complete
Epoch 3 complete
Epoch 4 complete
Epoch 5 complete
Epoch 6 complete
Epoch 7 complete
Epoch 8 complete
Epoch 9 complete
Epoch 10 complete
Epoch 11 complete
Epoch 12 complete
Epoch 13 complete
Epoch 14 complete
Epoch 15 complete
Epoch 16 complete
Epoch 17 complete
Epoch 18 complete
Epoch 19 complete
Epoch 20 complete
Epoch 21 complete
Epoch 22 complete
Epoch 23 complete
Epoch 24 complete
Epoch 25 complete
Epoch 26 complete
Epoch 27 complete
Epoch 28 complete
Epoch 29 complete
Epoch 30 complete
Epoch 31 complete
Epoch 32 complete
Epoch 33 complete
Epoch 34 complete
Epoch 35 complete
Epoch 36 complete
Epoch 37 complete
Epoch 38 complete
Epoch 39 complete
Epoch 40 complete
Epoch 41 complete
Epoch 42 complete
Epoch 43 complete
Epoch 44 complete
Epoch 45 complete
Epoch 46 complete
Epoch 47 complete
Epoch 48 complete
Epoch 49 complete
Epoch 50 complete
Epoch 51 complete
Epoch 52 complete
Epoch 53 complete
Epoch 54 complete
Epoch 55 complete
Ep

In [6]:
mynet.feedforward(data[0][0])

array([[0.9570759]])

In [8]:
for datum in data:
    print(mynet.feedforward(datum[0]))

[[0.9570759]]
[[0.03313558]]
[[0.01108016]]
[[0.03244206]]


In [9]:
data[0][0]

array([[1],
       [1]])

In [10]:
data

[(array([[1],
         [1]]), array([[1]])), (array([[0],
         [1]]), array([[0]])), (array([[0],
         [0]]), array([[0]])), (array([[1],
         [0]]), array([[0]]))]

In [11]:
data = [data[2], data[1], data[3], data[0]]

In [12]:
data

[(array([[0],
         [0]]), array([[0]])), (array([[0],
         [1]]), array([[0]])), (array([[1],
         [0]]), array([[0]])), (array([[1],
         [1]]), array([[1]]))]

In [13]:
for x in data:
    print(x)

(array([[0],
       [0]]), array([[0]]))
(array([[0],
       [1]]), array([[0]]))
(array([[1],
       [0]]), array([[0]]))
(array([[1],
       [1]]), array([[1]]))


In [14]:
mynet.reset()

In [15]:
mynet.SGD(data[:], 1000, 1, 1)

Epoch 0 complete
Epoch 1 complete
Epoch 2 complete
Epoch 3 complete
Epoch 4 complete
Epoch 5 complete
Epoch 6 complete
Epoch 7 complete
Epoch 8 complete
Epoch 9 complete
Epoch 10 complete
Epoch 11 complete
Epoch 12 complete
Epoch 13 complete
Epoch 14 complete
Epoch 15 complete
Epoch 16 complete
Epoch 17 complete
Epoch 18 complete
Epoch 19 complete
Epoch 20 complete
Epoch 21 complete
Epoch 22 complete
Epoch 23 complete
Epoch 24 complete
Epoch 25 complete
Epoch 26 complete
Epoch 27 complete
Epoch 28 complete
Epoch 29 complete
Epoch 30 complete
Epoch 31 complete
Epoch 32 complete
Epoch 33 complete
Epoch 34 complete
Epoch 35 complete
Epoch 36 complete
Epoch 37 complete
Epoch 38 complete
Epoch 39 complete
Epoch 40 complete
Epoch 41 complete
Epoch 42 complete
Epoch 43 complete
Epoch 44 complete
Epoch 45 complete
Epoch 46 complete
Epoch 47 complete
Epoch 48 complete
Epoch 49 complete
Epoch 50 complete
Epoch 51 complete
Epoch 52 complete
Epoch 53 complete
Epoch 54 complete
Epoch 55 complete
Ep

In [16]:
for x in data:
    arg = x[0].T.tolist()
    val = mynet.feedforward(x[0])
    print("{}: {}".format(arg, val))

[[0, 0]]: [[0.00107493]]
[[0, 1]]: [[0.02271895]]
[[1, 0]]: [[0.02794152]]
[[1, 1]]: [[0.96137192]]


In [21]:
def column(lst):
    return np.array([lst]).T
def uncolumn(vec):
    return vec.T.tolist()[0]
x = column([1,2,3])
print(repr(x))
uncolumn(x)

array([[1],
       [2],
       [3]])


[1, 2, 3]

In [22]:
for x, _ in data:
    print("{}: {}".format(
        uncolumn(x),
        mynet.feedforward(x)
    ))

[0, 0]: [[0.00107493]]
[0, 1]: [[0.02271895]]
[1, 0]: [[0.02794152]]
[1, 1]: [[0.96137192]]


In [24]:
 _     _   _    _
| 1 2 3 | | 0.32 |
| 4 5 6 | | 2.32 | = 
|_7 8 9_| |_42.2_|

SyntaxError: invalid syntax (<ipython-input-24-2f586edcad83>, line 2)